version: "3.9"

services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - iamdb:/data/db
  postgres:
    image: postgres:alpine3.14
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=digitalinventory
      - POSTGRES_PASSWORD=P@ssword
    volumes:
      - postgresdb:/var/lib/postgresql/data
  proxy:
    image: htetlinmaung/proxy
    ports:
      - "80:80"
  iam:
    image: htetlinmaung/iam:1.1.0
    ports:
      - "5000:5000"
  digitalinventory:
    image: htetlinmaung/digitalinventory:1.1.0
    ports:
      - "8080:8080"
  digitalinventoryweb:
    image: htetlinmaung/digitalinventoryweb:1.1.0
    ports:
      - "3000:3000"
  nodeproxy:
    image: htetlinmaung/nodeproxy:1.0.0
    ports:
      - "7070:7070"
  startup:
    image: htetlinmaung/startup:1.0.0
volumes:
  iamdb:
  postgresdb: