version: "3.9"

services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - iamdb:/data/db
  postgres:
    image: postgres:alpine3.14
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=digitalinventory
      - POSTGRES_PASSWORD=P@ssword
    volumes:
      - postgresdb:/var/lib/postgresql/data
  proxy:
    image: htetlinmaung/proxy:1.0.0
    ports:
      - "80:80"
  iam:
    image: htetlinmaung/iam:1.1.0
    ports:
      - "5000:5000"
  digitalinventory:
    image: htetlinmaung/digitalinventory:1.1.0
    ports:
      - "8080:8080"
  digitalinventoryweb:
    image: htetlinmaung/digitalinventoryweb:1.1.0
    ports:
      - "3000:3000"
  nodeproxy:
    image: htetlinmaung/nodeproxy:1.0.0
    ports:
      - "7070:80"
  startup:
    image: htetlinmaung/startup:1.0.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  storage:
    image: htetlinmaung/storage:1.0.0
    volumes:
      - /app/storage/public:/app/public
  juice:
    image: htetlinmaung/juice:1.0.0
    ports:
      - "7071:80"
  pyopenai:
    image: htetlinmaung/pyopenai:1.0.0
  openai:
    image: htetlinmaung/openai:1.0.0
    volumes:
      - /app/openai/public:/app/public
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  musifyserver:
    image: htetlinmaung/musifyserver:1.0.0
    volumes:
      - /home/hlm/app/musifyserver/storage:/app/storage
    ports:
      - "3002:3002"
    environment:
      - DB_CONNECTION=mongodb://mongo:27017/musifydb
  fetchit:
    image: htetlinmaung/fetchit:1.0.0
    ports:
      - "4001:3000"
    environment:
      - REDIS_URL=redis://redis:6379
  animelux:
    image: htetlinmaung/animelux:1.0.0
  prettyapiserver:
    image: htetlinmaung/prettyapiserver:1.0.0
    ports:
      - "4020:4020"
    environment:
      - DB_CONNECTION=mongodb://mongo:27017/prettyapidb
      - JWT_SECRET=09f46a0a2d4b8b1cdd8a002e35da18b6
    volumes:
      - /app/prettyapiserver/public:/app/public
  prettyapi:
    image: htetlinmaung/prettyapi:1.0.0
  appmanagement:
    image: htetlinmaung/appmanagement:1.0.0
    ports:
      - "3020:3020"
    environment:
      - DB_CONNECTION=mongodb://mongo:27017/appmanagementdb
      - JWT_SECRET=09f46a0a2d4b8b1cdd8a002e35da18b6
    volumes:
      - /app/appmanagement/storage:/app/storage
      

volumes:
  iamdb:
  postgresdb: